config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get 'searches/search'
  end
  namespace :public do
    get 'menus/new'
    get 'menus/edit'
    get 'menus/show'
  end
  namespace :public do
    get 'users/show'
    get 'users/edit'
  end
  namespace :public do
    get 'posts/index'
    get 'posts/show'
    get 'posts/edit'
  end
  #管理者
  devise_for :admin, skip: [:registrations, :passwords] ,controllers:{
    sessions:"admin/sessions"
  }

  #ユーザー用
  devise_for :users, skip: [:passwords], controllers:{
    registrations:"public/registrations",
    sessions:'public/sessions'
  }

  devise_scope :user do
    post 'users_guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    root to: 'homes#top'
    get "/about" => "homes#about", as: 'about'
    get 'search' => "searches#search"
    resources :posts, only: [:index,:show,:edit,:create,:destroy,:update] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end

    resources :users, only: [:show,:edit,:update] do
      resource :relationships, only: [:create, :destroy]
    	get 'followings' => 'relationships#followings', as: 'followings'
    	get 'followers' => 'relationships#followers', as: 'followers'
    end

    resources :menus, only: [:edit,:new,:show,:create,:destroy,:update]
    get 'users/:id/menus' => "users#menus", as: 'usermenus'
    get 'mypage/show' => "users#mypage", as: 'mypage'
    get 'mypage/favo' => "users#mypagefavo", as: 'mypagefavo'
    get 'mypage/menus' => "users#mypagemenus", as: 'mypagemenus'
  end

  namespace :admin do
    devise_scope :admin do
    root "sessions#new"
    end
    get "top" => "homes#top"
    resources :users, only: [:index, :destroy]
    resources :posts, only: [:index, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/views/admin/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2 class="mt-4 rounded-lg border border-dark text-center">会員TOP画面</h2>
    </div>
  </div>
  <div class="row">
    <div class="col mx-2 text-danger">
      ※ここは、管理者のためのページです。
      個人情報等が表示されますので、取り扱いの際は、周囲を確認の上ご利用ください

    </div>
  </div>
  <div class="row mt-4" style="height: 600px;">
    <div class="col mx-2">
      現在は以下の項目が管理可能です。<br>
      <%= link_to(admin_posts_path) do %>
      ・投稿一覧
      <% end %><br>
      <%= link_to(admin_users_path) do %>
      ・会員一覧
      <% end %>
    </div>
  </div>
</div>