config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get 'searches/search'
  end
  namespace :public do
    get 'menus/new'
    get 'menus/edit'
    get 'menus/show'
  end
  namespace :public do
    get 'users/show'
    get 'users/edit'
  end
  namespace :public do
    get 'posts/index'
    get 'posts/show'
    get 'posts/edit'
  end
  #管理者
  devise_for :admin, skip: [:registrations, :passwords] ,controllers:{
    sessions:"admin/sessions"
  }

  #ユーザー用
  devise_for :users, skip: [:passwords], controllers:{
    registrations:"public/registrations",
    sessions:'public/sessions'
  }

  devise_scope :user do
    post 'users_guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    root to: 'homes#top'
    get "/about" => "homes#about", as: 'about'
    get 'search' => "searches#search"
    resources :posts, only: [:index,:show,:edit,:create,:destroy,:update] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end

    resources :users, only: [:show,:edit,:update] do
      resource :relationships, only: [:create, :destroy]
    	get 'followings' => 'relationships#followings', as: 'followings'
    	get 'followers' => 'relationships#followers', as: 'followers'
    end

    resources :menus, only: [:edit,:new,:show,:create,:destroy,:update]
    get 'users/:id/menus' => "users#menus", as: 'usermenus'
    get 'mypage/show' => "users#mypage", as: 'mypage'
    get 'mypage/favo' => "users#mypagefavo", as: 'mypagefavo'
    get 'mypage/menus' => "users#mypagemenus", as: 'mypagemenus'
  end

  namespace :admin do
    devise_scope :admin do
    root "sessions#new"
    end
    get "top" => "homes#top"
    resources :users, only: [:index, :destroy]
    resources :posts, only: [:index, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true, length:{ maximum:20 }
  validates :content, presence: true

#いいねがあるならfalseを返す
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.looks(word)
    #空白ならば全部載せるそれ以外は、部分検索
    unless word == ""
      @post = Post.where(["title LIKE? OR content LIKE?","%#{word}%","%#{word}%"])
    else
      @post = Post.all
    end
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController

  def index
    @posts = Post.page(params[:page]).per(10)
  end
#destroy
  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      redirect_to admin_posts_path
    else render 'index'
    end
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2 class="mt-4 rounded-lg border border-dark text-center">投稿一覧</h2>
    </div>
  </div>
   <% #投稿一覧%>
  <div class="row mb-4">
    <% if @posts.count == 0 %>
      投稿は存在しません。
    <% end %>
    <% @posts.each do |post| %>
      <div class="container mt-4 border-bottom border-dark">
        <div class="row">
          <% #プロフィール画像 %>
          <div class="col-md-2">
            <%= image_tag post.user.get_profile_image(100,100) %>
          </div>
          <div class="col-md-8">
            ユーザー名：<%= post.user.name %>
            作成日時:<%= l post.created_at %><br>
            タイトル：<%= post.title %>
          </div>
          <div class="col-mb-2">
            <%= link_to admin_post_path(post), method: :delete, data: { confirm: '本当にBanしますか？' } do %>
              <button type="button" class="btn btn-danger">投稿をBanする</button>
            <% end %>
          </div>
        </div>
        <div class="row mt-2 mb-2">
          <div class="col-md-10 offset-md-2">
            コンテンツ：<%= post.content %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="row mt-1 d-flex align-items-center justify-content-center">
    <%= paginate @posts %>
</div>
</div>