config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get 'searches/search'
  end
  namespace :public do
    get 'menus/new'
    get 'menus/edit'
    get 'menus/show'
  end
  namespace :public do
    get 'users/show'
    get 'users/edit'
  end
  namespace :public do
    get 'posts/index'
    get 'posts/show'
    get 'posts/edit'
  end
  #管理者
  devise_for :admin, skip: [:registrations, :passwords] ,controllers:{
    sessions:"admin/sessions"
  }

  #ユーザー用
  devise_for :users, skip: [:passwords], controllers:{
    registrations:"public/registrations",
    sessions:'public/sessions'
  }

  devise_scope :user do
    post 'users_guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    root to: 'homes#top'
    get "/about" => "homes#about", as: 'about'
    get 'search' => "searches#search"
    resources :posts, only: [:index,:show,:edit,:create,:destroy,:update] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end

    resources :users, only: [:show,:edit,:update] do
      resource :relationships, only: [:create, :destroy]
    	get 'followings' => 'relationships#followings', as: 'followings'
    	get 'followers' => 'relationships#followers', as: 'followers'
    end

    resources :menus, only: [:edit,:new,:show,:create,:destroy,:update]
    get 'users/:id/menus' => "users#menus", as: 'usermenus'
    get 'mypage/show' => "users#mypage", as: 'mypage'
    get 'mypage/favo' => "users#mypagefavo", as: 'mypagefavo'
    get 'mypage/menus' => "users#mypagemenus", as: 'mypagemenus'
  end

  namespace :admin do
    devise_scope :admin do
    root "sessions#new"
    end
    get "top" => "homes#top"
    resources :users, only: [:index, :destroy]
    resources :posts, only: [:index, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :posts, dependent: :destroy
  has_many :menus, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  #中間テーブルを作成した
  has_many :relationships, class_name:"Relationship", foreign_key:"follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name:"Relationship", foreign_key:"followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :followings, through: :relationships, source: :followed
  has_one_attached :profile_image, dependent: :destroy

  validates :name, presence: true
#ゲスト機能
  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |user|
      #これでランダムな配列を作成することができる
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  def get_profile_image(width, height)
#画像搭載機能
    unless profile_image.attached?
      file_path =Rails.root.join('app/assets/images/swieetnoimage.png')
      profile_image.attach(io:File.open(file_path), filename:'default-image.jpg', content_type:'image/jpeg')
    end
    profile_image.variant(resize_to_limit:[width, height]).processed
  end
#フォロー機能
  def follow(user)
    relationships.create(followed_id: user.id)
  end
#フォロー機能
  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy
  end
#フォローしているかどうか判断
  def following?(user)
    followings.include?(user)
  end
#検索機能
  def self.looks(word)
    unless word == ""
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  ##ページを１０個の情報で区切れるようにした
  def index
    @users = User.page(params[:page]).per(10)
  end
##destroyに注意
  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to admin_users_path
    else render 'index'
    end
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2 class="mt-4 rounded-lg border border-dark text-center">会員一覧</h2>
    </div>
  </div>

  <div class="row">
    <table class="table">
      <thead>
        <tr>
          <th>#</th>
          <th>Profile Image</th>
          <th>Name</th>
          <th>E-mail</th>
          <th>Introduction</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
        <tr>
          <th><%= user.id %></th>
          <td><%= image_tag user.get_profile_image(100,100) %></td>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.introduction %></td>
          <td>
            <%= link_to admin_user_path(user), method: :delete, data: { confirm: '本当にBanしますか？' } do %>
              <button type="button" class="btn btn-danger">ユーザーをBanする</button>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <div class="row mt-1 d-flex align-items-center justify-content-center">
    <%= paginate @users %>
    </div>
  </div>
</div>