config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get 'searches/search'
  end
  namespace :public do
    get 'menus/new'
    get 'menus/edit'
    get 'menus/show'
  end
  namespace :public do
    get 'users/show'
    get 'users/edit'
  end
  namespace :public do
    get 'posts/index'
    get 'posts/show'
    get 'posts/edit'
  end
  #管理者
  devise_for :admin, skip: [:registrations, :passwords] ,controllers:{
    sessions:"admin/sessions"
  }

  #ユーザー用
  devise_for :users, skip: [:passwords], controllers:{
    registrations:"public/registrations",
    sessions:'public/sessions'
  }

  devise_scope :user do
    post 'users_guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    root to: 'homes#top'
    get "/about" => "homes#about", as: 'about'
    get 'search' => "searches#search"
    resources :posts, only: [:index,:show,:edit,:create,:destroy,:update] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end

    resources :users, only: [:show,:edit,:update] do
      resource :relationships, only: [:create, :destroy]
    	get 'followings' => 'relationships#followings', as: 'followings'
    	get 'followers' => 'relationships#followers', as: 'followers'
    end

    resources :menus, only: [:edit,:new,:show,:create,:destroy,:update]
    get 'users/:id/menus' => "users#menus", as: 'usermenus'
    get 'mypage/show' => "users#mypage", as: 'mypage'
    get 'mypage/favo' => "users#mypagefavo", as: 'mypagefavo'
    get 'mypage/menus' => "users#mypagemenus", as: 'mypagemenus'
  end

  namespace :admin do
    devise_scope :admin do
    root "sessions#new"
    end
    get "top" => "homes#top"
    resources :users, only: [:index, :destroy]
    resources :posts, only: [:index, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
  
  belongs_to :theme
  
  validates :meter, presence: true
  validates :repeat, presence: true
  validates :set, presence: true
  validates :second, presence: true
  validates :detail, presence: true
  #メニューのタイムの合計を出すメソッドを作成
  def sum_seconds
    second * set * repeat
  end 
  #メニューの距離の合計を出すメソッドを作成
  def sum_meters
    meter * repeat * set
  end 
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
end

app/models/menu.rb
class Menu < ApplicationRecord

  belongs_to :user
  has_many :themes, dependent: :destroy
  accepts_nested_attributes_for :themes, allow_destroy: true
#存在したらOk
  validates :title, presence: true
  validates :dating, presence: true


end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true, length:{ maximum:20 }
  validates :content, presence: true

#いいねがあるならfalseを返す
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.looks(word)
    #空白ならば全部載せるそれ以外は、部分検索
    unless word == ""
      @post = Post.where(["title LIKE? OR content LIKE?","%#{word}%","%#{word}%"])
    else
      @post = Post.all
    end
  end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :user
  belongs_to :post

  validates :content, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name:"User"
  belongs_to :followed, class_name:"User"
end

app/models/theme.rb
class Theme < ApplicationRecord

belongs_to :menu
has_many :contents, dependent: :destroy
accepts_nested_attributes_for :contents, allow_destroy: true

validates :style, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :posts, dependent: :destroy
  has_many :menus, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  #中間テーブルを作成した
  has_many :relationships, class_name:"Relationship", foreign_key:"follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name:"Relationship", foreign_key:"followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :followings, through: :relationships, source: :followed
  has_one_attached :profile_image, dependent: :destroy

  validates :name, presence: true
#ゲスト機能
  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |user|
      #これでランダムな配列を作成することができる
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  def get_profile_image(width, height)
#画像搭載機能
    unless profile_image.attached?
      file_path =Rails.root.join('app/assets/images/swieetnoimage.png')
      profile_image.attach(io:File.open(file_path), filename:'default-image.jpg', content_type:'image/jpeg')
    end
    profile_image.variant(resize_to_limit:[width, height]).processed
  end
#フォロー機能
  def follow(user)
    relationships.create(followed_id: user.id)
  end
#フォロー機能
  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy
  end
#フォローしているかどうか判断
  def following?(user)
    followings.include?(user)
  end
#検索機能
  def self.looks(word)
    unless word == ""
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController

  def index
    @posts = Post.page(params[:page]).per(10)
  end
#destroy
  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      redirect_to admin_posts_path
    else render 'index'
    end
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  ##ページを１０個の情報で区切れるようにした
  def index
    @users = User.page(params[:page]).per(10)
  end
##destroyに注意
  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to admin_users_path
    else render 'index'
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  

  protected

  def after_sign_in_path_for(resource)
    case resource
    when Admin
    admin_top_path
    when User
    posts_path
    end
  end

  def after_sign_out_path_for(resource)
    if resource == :admin
         admin_root_path
    else
         root_path
    end
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer text-center" style="height:80px; bottom:0px; left:0px; right:0px;">©syanswim</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg header-content">
    <div class="brand">
      <%= link_to(root_path,class:"navbar-brand",style:"opacity: 0.8;") do %>
      <%= image_tag 'dolphin.png', :size =>'200x60' %>
      <% end %>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon mt-1"><i class="fa-solid fa-bars"></i></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
    <div>
      <% if user_signed_in? %>
      <ul  style="opacity: 1;">
        <%#投稿一覧ボタン%>
        <%= link_to(posts_path) do %>
          <button class="btn"><%= image_tag 'Swieet.png', :size =>'30x30'%></button>
        <% end %>
        <%#マイページボタン%>
        <%= link_to(mypage_path) do %>
            <button class="btn"><%= image_tag 'mypage.png', :size =>'30x30' %></button>
        <% end %>
        <%#メニューボタン%>
        <%= link_to(mypagemenus_path) do %>
           <button class="btn"><%= image_tag 'menu.png', :size =>'30x30' %></button>
        <% end %>
        <%#ログアウトボタン%>
        <%= link_to(destroy_user_session_path,method: :delete) do %>
          <button class="btn"><%= image_tag 'logout.png', :size =>'30x30' %></button>
        <% end %>
      </ul>

      <% elsif admin_signed_in? %>
      <ul  style="opacity: 1;">
        <%= link_to(admin_top_path) do %>
          <button type="button" class="btn"><%= image_tag 'mypage.png', :size =>'30x30' %></button>
        <% end %>
        <%= link_to(admin_posts_path) do %>
          <button type="button" class="btn"><%= image_tag 'Swieet.png', :size =>'30x30' %></button>
        <% end %>
        <%= link_to(admin_users_path) do %>
          <button type="button" class="btn"><%= image_tag 'registration.png', :size =>'30x30' %></button>
        <% end %>
        <%= link_to(destroy_admin_session_path,method: :delete) do %>
        <button type="button" class="btn"><%= image_tag 'logout.png', :size =>'30x30' %></button>
        <% end %>
      </ul>
      <% else %>
      <ul  style="opacity: 1;">
        <%= link_to(new_user_session_path) do %>
        <button type="button" class="font-head btn"><b>Login</b><%= image_tag 'login.png', :size =>'30x30' %></button>
        <% end %>
        <%= link_to(new_user_registration_path) do %>
        <button type="button" class="font-head btn"><b>会員登録</b><%= image_tag 'registration.png', :size =>'30x30' %></button>
        <% end %>
        <%= link_to(about_path) do %>
        <button type="button" class="font-head btn"><b>Swieetについて</b></button>
        <% end %>
      </ul>
      <% end %>
    </div>
   </div>
  </nav>
</header>

app/views/layouts/_searchform.html.erb
<%= form_with url: search_path, method: :get, local: :true do |f| %>
<div class="wraps mt-4">
   <div class="search">
      <%= f.text_field :word,class:"searchTerm", placeholder:"ユーザーや投稿を検索" %>
      <%= button_tag(type: "submit", class: "searchButton") do %>
        <i class="fa fa-search"></i>
      <% end %>
   </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Swieet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/d3bda943a9.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Serif+JP&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>